name: test1
on:
  watch:
    types: started
  # schedule:
  #  - cron: '*/15 * * * *'
  repository_dispatch:
    types: webhook
jobs:    
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          body: ${{github.event.client_payload.body}}
        run: |
          echo body: $body
  doTheRestOfTheWork:
    runs-on: ubuntu-latest
    environment: delayTest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: https://69ab-221-222-21-238.ngrok.io/shopify/action
          method: POST
          data: '{"data": "${{ github.event.client_payload.body }}","name": "orders_unfulfilled_noti"}'